config/routes.rb
Rails.application.routes.draw do
  resources :xxxes
  resources :courses
  get 'pages/about'
  get 'pages/location'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/xxx.rb
class Xxx < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:image, :video, :title, :star, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def location
  end
end

app/controllers/xxxes_controller.rb
class XxxesController < ApplicationController
  before_action :set_xxx, only: [:show, :edit, :update, :destroy]

  # GET /xxxes
  # GET /xxxes.json
  def index
    @xxxes = Xxx.all
  end

  # GET /xxxes/1
  # GET /xxxes/1.json
  def show
  end

  # GET /xxxes/new
  def new
    @xxx = Xxx.new
  end

  # GET /xxxes/1/edit
  def edit
  end

  # POST /xxxes
  # POST /xxxes.json
  def create
    @xxx = Xxx.new(xxx_params)

    respond_to do |format|
      if @xxx.save
        format.html { redirect_to @xxx, notice: 'Xxx was successfully created.' }
        format.json { render :show, status: :created, location: @xxx }
      else
        format.html { render :new }
        format.json { render json: @xxx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xxxes/1
  # PATCH/PUT /xxxes/1.json
  def update
    respond_to do |format|
      if @xxx.update(xxx_params)
        format.html { redirect_to @xxx, notice: 'Xxx was successfully updated.' }
        format.json { render :show, status: :ok, location: @xxx }
      else
        format.html { render :edit }
        format.json { render json: @xxx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xxxes/1
  # DELETE /xxxes/1.json
  def destroy
    @xxx.destroy
    respond_to do |format|
      format.html { redirect_to xxxes_url, notice: 'Xxx was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xxx
      @xxx = Xxx.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xxx_params
      params.require(:xxx).permit(:image, :video, :title, :star, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/xxxes_helper.rb
module XxxesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.text_field :video %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :star %>
    <%= form.number_field :star %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>
<%= render 'form', course: @course %>
<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<%= link_to new_course_path, class:"btn-floating btn-large waves-effect waves-light red" do %>
  <i class="material-icons">add</i>
<% end %>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.title, course %></td>
        <td>
         <%= link_to edit_course_path(course) do %>
         <i class="material-icons">edit</i>
         <%end %>
         <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' } do %>          
         <i class="material-icons">delete</i>
         <%end %>
        </td>
       </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<div class="row">
  <div class="col m12">
    <div class="card blue-grey darken-1">
        <div class="card-image">
         <iframe src="//fast.wistia.net/embed/iframe/#{#course.video}" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="100%" height="349"></iframe>
        <script src="//fast.wistia.net/assets/external/E-v1.js" async></script> 
        </div>

      <div class="card-content white-text">
        <div class="row">
          <div class="col m4 center">
              
          </div>
          <div class="col m8">
          <span class="card-title"><%= @course.title %></span> <p><%= @course.description %></p>         
        </div>
       </div>
      </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frontend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript" src="./lib/jquery-3.3.1.min.js"></script>
  </head>

  <body>

  
  <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Logo</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">Javascript</a></li>
    <li><a href="mobile.html">Mobile</a></li>
  </ul>
          

  
      <%= yield %>
    </body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>
<div class="card z-depth-3">
	<div class="card-content white-text">
		<div class="row">
		<div class="col m6">
		<a class="twitter-timeline" data-width="500" href="https://twitter.com/AnhBui22399662?ref_src=twsrc%5Etfw">Tweets by AnhBui22399662</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>	
		</div>	
  		<div class="col m6">
  		<div class="card-panel teal lighten-1 z-depth-1">
  		<div class="row">
  		<div class="col m3">
		<%= image_tag "1111.png", class: "circle responsive-img" %>

  		</div>	
  		<div class="col m9">
  		<span class="white-text">
 		<h5>Anh Bui</h5>
 		How to code in Rails ?
 		</span>
 		</div>

        </div>
  		</div>
  		</div>
		</div>
	</div>
</div>

app/views/pages/location.html.erb
<h1>Pages#location</h1>
<p>Find me in app/views/pages/location.html.erb</p>

<h2>Location</h2>
<div class="card z-depth-3">
    <div class="card-content black-text">
   	 <div class="row">
   		Here is where you want to go<br/> 
   		 <iframe
		width="600"
  		height="450"
  		frameborder="0" style="border:0"
  		src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBFKDKowUTgk6TXvKnPCNk1_l8Sj5lhD6U
    	&q=Space+Needle,Seattle+WA" allowfullscreen>
</iframe>


   	   	
 </div>    
   	 </div>
</div>

app/views/xxxes/_form.html.erb
<%= form_with(model: xxx, local: true) do |form| %>
  <% if xxx.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(xxx.errors.count, "error") %> prohibited this xxx from being saved:</h2>

      <ul>
        <% xxx.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.text_field :video %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :star %>
    <%= form.number_field :star %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/xxxes/edit.html.erb
<h1>Editing Xxx</h1>

<%= render 'form', xxx: @xxx %>

<%= link_to 'Show', @xxx %> |
<%= link_to 'Back', xxxes_path %>

app/views/xxxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Xxxes</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Video</th>
      <th>Title</th>
      <th>Star</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xxxes.each do |xxx| %>
      <tr>
        <td><%= xxx.image %></td>
        <td><%= xxx.video %></td>
        <td><%= xxx.title %></td>
        <td><%= xxx.star %></td>
        <td><%= xxx.description %></td>
        <td><%= link_to 'Show', xxx %></td>
        <td><%= link_to 'Edit', edit_xxx_path(xxx) %></td>
        <td><%= link_to 'Destroy', xxx, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xxx', new_xxx_path %>

app/views/xxxes/new.html.erb
<h1>New Xxx</h1>

<%= render 'form', xxx: @xxx %>

<%= link_to 'Back', xxxes_path %>

app/views/xxxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @xxx.image %>
</p>

<p>
  <strong>Video:</strong>
  <%= @xxx.video %>
</p>

<p>
  <strong>Title:</strong>
  <%= @xxx.title %>
</p>

<p>
  <strong>Star:</strong>
  <%= @xxx.star %>
</p>

<p>
  <strong>Description:</strong>
  <%= @xxx.description %>
</p>

<%= link_to 'Edit', edit_xxx_path(@xxx) %> |
<%= link_to 'Back', xxxes_path %>